### PR TITLE
implement Panic() and PanicF() interfaces for slf4go

### PR DESCRIPTION
**Pull request by aellwein**
Panic() and PanicF() may have quite different semantic as Fatal/FatalF,
for the detailed explanation please read here:

https://stackoverflow.com/a/35997323

### CODE REVIEW

**Comment by aellwein** [comment]
i want to develop this further, so PR will follow later

**Comment by aellwein** [comment]
@sisyphsu i've just realized it is not possible for me to do a PR against this repository anymore, 
because my fork is developed in an other direction: using separate repositories as logging implementations. Please feel free to review and comment my work here: [https://github.com/aellwein/slf4go](https://github.com/aellwein/slf4go)

**Comment by sisyphsu** [comment]
very sorry for didn't replay timely...
i don't have time to continue this project currently, so please feel free to fork and modify this library.
i think you are right, mix interface and implementations in one repository wasn't a good decision

**Comment by aellwein** [comment]
Thanks!

**Pull request closed without merging**
